// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-document view a new tab opens in (see `AppConfig::default_view_mode`).
 */
export type DefaultViewMode = "edit" | "split" | "preview";
