// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalSplitDir } from "./TerminalSplitDir";

/**
 * One node of a persisted terminal split layout (see
 * `AppConfig::terminal_layouts` and frontend/src/split-layout.ts).
 */
export type TerminalLayout = { "type": "pane", session: string, } | { "type": "split", dir: TerminalSplitDir, ratio: number, a: TerminalLayout, b: TerminalLayout, };
