// Internal app events on the EventBus.
export const EVENTS = {
  CONTENT_CHANGED: 'content-changed',
  CURSOR_CHANGED: 'cursor-changed',
  SCROLL_SYNC: 'scroll-sync',
  PREVIEW_SCROLL: 'preview-scroll',
  PREVIEW_TOGGLED: 'preview-toggled',
  SIDEBAR_TOGGLED: 'sidebar-toggled',
  WORD_WRAP_CHANGED: 'word-wrap-changed',
  THEME_CHANGED: 'theme-changed',
  TAB_SWITCHED: 'tab-switched',
  TAB_SAVE_STATE: 'tab-save-state',
  TAB_SAVED: 'tab-saved',
  TAB_CLOSED: 'tab-closed',
  CONFIRM_CLOSE_TAB: 'confirm-close-tab',
  ALL_TABS_CLOSED: 'all-tabs-closed',
  FILE_TREE_OPEN: 'file-tree-open',
  TOC_GOTO_LINE: 'toc-goto-line',
  TOC_SCROLL_PREVIEW: 'toc-scroll-preview',
  INSERT_AT_CURSOR: 'insert-at-cursor',
} as const;

// Tauri events sent from the Rust menu handler. Mirror of menu IDs in
// src-tauri/src/menu.rs — the Rust side emits `menu:<id>`. Keep in sync.
export const MENU = {
  NEW_FILE: 'menu:new-file',
  NEW_TAB: 'menu:new-tab',
  OPEN_FILE: 'menu:open-file',
  OPEN_FOLDER: 'menu:open-folder',
  OPEN_REMOTE: 'menu:open-remote',
  SAVE: 'menu:save',
  SAVE_AS: 'menu:save-as',
  EXPORT_HTML: 'menu:export-html',
  CLOSE_TAB: 'menu:close-tab',
  FIND: 'menu:find',
  // View menu: the per-document view (title bar Edit | Split | Preview | Diff).
  VIEW_EDIT: 'menu:view-edit',
  VIEW_SPLIT: 'menu:view-split',
  VIEW_PREVIEW: 'menu:view-preview',
  VIEW_DIFF: 'menu:view-diff',
  TOGGLE_TERMINAL: 'menu:toggle-terminal',
  TOGGLE_TERMINALS_ONLY: 'menu:toggle-terminals-only',
  TERMINAL_SPLIT_RIGHT: 'menu:terminal-split-right',
  TERMINAL_SPLIT_DOWN: 'menu:terminal-split-down',
  TERMINAL_CLOSE_PANE: 'menu:terminal-close-pane',
  TERMINAL_FOCUS_NEXT: 'menu:terminal-focus-next',
  TERMINAL_FOCUS_PREV: 'menu:terminal-focus-prev',
  TOGGLE_SIDEBAR: 'menu:toggle-sidebar',
  TOGGLE_WORD_WRAP: 'menu:toggle-word-wrap',
  TOGGLE_THEME: 'menu:toggle-theme',
  TOGGLE_HTML_JS: 'menu:toggle-html-js',
  SHOW_SHORTCUTS: 'menu:show-shortcuts',
  SHOW_SETTINGS: 'menu:show-settings',
  CHECK_UPDATES: 'menu:check-updates',
  SHOW_FILES: 'menu:show-files',
  SHOW_CHANGES: 'menu:show-changes',
  SEARCH_IN_FILES: 'menu:search-in-files',
  QUICK_OPEN: 'menu:quick-open',
  COMMAND_PALETTE: 'menu:command-palette',
  QUIT: 'menu:quit',
  OPEN_FILE_PATH: 'open-file-path',
} as const;

// User actions emitted by toolbar buttons / shortcuts.
export const ACTIONS = {
  NEW_FILE: 'action:new-file',
  OPEN_FILE: 'action:open-file',
  OPEN_FOLDER: 'action:open-folder',
  OPEN_REMOTE: 'action:open-remote',
  SAVE: 'action:save',
  SAVE_AS: 'action:save-as',
  CLOSE_TAB: 'action:close-tab',
  EXPORT_HTML: 'action:export-html',
  FIND: 'action:find',
  QUIT: 'action:quit',
  BOLD: 'action:bold',
  ITALIC: 'action:italic',
  HEADING: 'action:heading',
  UNORDERED_LIST: 'action:unordered-list',
  ORDERED_LIST: 'action:ordered-list',
  CODE_BLOCK: 'action:code-block',
  INLINE_CODE: 'action:inline-code',
  QUOTE: 'action:quote',
  LINK: 'action:link',
  IMAGE: 'action:image',
  TABLE: 'action:table',
  TOGGLE_SIDEBAR: 'action:toggle-sidebar',
  TOGGLE_PREVIEW: 'action:toggle-preview',
  TOGGLE_TERMINAL: 'action:toggle-terminal',
  TOGGLE_TERMINALS_ONLY: 'action:toggle-terminals-only',
  TOGGLE_EDITOR: 'action:toggle-editor',
  /** Set the active document's view (payload: { mode }). */
  SET_VIEW_MODE: 'action:set-view-mode',
  TOGGLE_WRAP: 'action:toggle-wrap',
  /** Open CodeMirror's go-to-line prompt (status bar Ln/Col). */
  GOTO_LINE: 'action:goto-line',
  /** Settings, scrolled to the Agents section (status bar agent tools). */
  SHOW_AGENT_SETTINGS: 'action:show-agent-settings',
  TOGGLE_THEME: 'action:toggle-theme',
  NEXT_TAB: 'action:next-tab',
  PREV_TAB: 'action:prev-tab',
  SHOW_SHORTCUTS: 'action:show-shortcuts',
  SHOW_SETTINGS: 'action:show-settings',
  /** Activity bar: open the sidebar on a view (clicking the active one closes it). */
  SHOW_SIDEBAR_VIEW: 'action:show-sidebar-view',
  QUICK_OPEN: 'action:quick-open',
  COMMAND_PALETTE: 'action:command-palette',
} as const;

/** Any bus action name (ACTIONS.*). */
export type ActionName = (typeof ACTIONS)[keyof typeof ACTIONS];
